---
title: Trusted by design
subtitle: set up your research software for community adoption
author: Niko Sirmpilatze @ FOSDEM 2026
date: 2026-02-01 
format:
  revealjs:
    footer: "[neuroinformatics.dev/slides-trusted-by-design](https://neuroinformatics.dev/slides-trusted-by-design/)"
links:
   movement: "https://movement.neuroinformatics.dev"
   slides: "https://neuroinformatics.dev/slides-trusted-by-design/"
   blog: "https://neuroinformatics.dev/blog/trusted-by-design_intro.html"
---

## Contents

We can use all the normal markdown features here, like:

- Bullet lists
- **Bold text**
- *Italic text*
- `Inline code`

::: aside
[See also example RevealJS slides in the Quarto docs.](https://quarto.org/docs/presentations/revealjs/)
:::

## Just a code block, nothing gets executed...

... but there is some fancy highlighting

```{.python code-line-numbers="1|3|4-9"}
from pathlib import Path

home_path = Path.home()
if home_path.exists():
  data_path = home_path / "data"
else:
  pass
  # raise some error maybe?
```

## Link and a preview a webpage:

::: {style="text-align: center; margin-top: 1em"}
[interoperable Python-based tools for computational neuroanatomy](https://brainglobe.info/index.html){preview-link="true" style="text-align: center"}
:::

## Use a variable several times

Variables defined in the metadata is re-useable anywhere

* {{< meta links.movement >}}
* {{< meta links.blog >}}

## Admonitions / Callouts

:::{.callout-note}
## Note Callout

This is a note callout.
:::

:::{.callout-tip}
## Tip Callout

This is a tip callout.
:::

:::{.callout-warning}
## Warning Callout

This is a warning callout.
:::

## Citing references

- To cite references, include them in the `references.bib` BibTeX file
and then use the syntax `[@citekey]` to cite them.
- For example, our preprint of the Blackcap brain atlas [@blackcap_preprint].
- You can preview the reference entry by hovering over the citation, cool!

::: aside
[Read more about Quarto citations](https://quarto.org/docs/authoring/citations.html#sec-citations).
:::

## References {.smaller}

This is how you create a references section, i.e. a bibliography.

::: {#refs}
:::
